### PR TITLE
First installation fixes and .gitignore update

### PR DESCRIPTION
**Pull request by ajira86**

### CODE REVIEW

**Comment by ajira86** [comment]
Github has automatically added commit 896ba7f, so I have to create a branch for future pull request :/
I let you evaluate if it can help

**Comment by ajira86** [comment]
I saw the bzignore file that have the same structure as a gitignore fyi

**Comment by Ppjet6** [comment]
You should remove the composer.lock from the .gitignore file. See [composer's recommendations](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-file).

**Comment by ajira86** [comment]
@Ppjet6 :+1:

**Comment by edhelas** [comment]
Thanks for the PR :) 

In system.tpl you cannot put quotes around the two values. The first one is a hash that need to be displayed correctly in Javascript, and the second one is a boolean :p So maybe we can write some test in the controller to fix this ?

**Comment by edhelas** [comment]
Linked with the issue #8

**Comment by edhelas** [comment]
The changes are now in trunk, see this commit https://github.com/edhelas/movim/commit/97f96daa038dcc07e63d12710bab9982b4d844af

**Pull request closed without merging**
