### PR TITLE
Log errors if interprocess communication fails

### PR DESCRIPTION
**Pull request by mirabilos**
This aids searching for errors. We’re currently tracking a 500 Internal Server Error being retuned by the API…

### CODE REVIEW

**Comment by mirabilos** [comment]
Eh, no, this is totally wrong. `curl_errno()` is 0 when _no_ error occurred.

Whyever an HTTP 500 is not reported as error is… weird.

**Comment by edhelas** [comment]
I'd also prefer to rain an Exception as Movim can properly catch them https://github.com/movim/movim/blob/master/src/Movim/Bootstrap.php#L313 :)

**Comment by mirabilos** [comment]
Hmh. The exception *is* raised, around line 300 of `StreamingServer.php`. I’m currently hoping it would contain more information about why chatting does not work.

**Comment by mirabilos** [comment]
cURL is worse:

>  Note that response status codes which indicate errors (such as 404 Not found) are not regarded as failure. curl_getinfo() can be used to check for these. 

So, apparently, one has to check what `curl_getinfo($ch, CURLINFO_HTTP_CODE)` returns. Meh. Sorry about the noise.

**Pull request closed without merging**
