### PR TITLE
Verify shared picture size when proxying

### PR DESCRIPTION
**Pull request by dos1**

### CODE REVIEW

**Comment by edhelas** [comment]
Do you think it's better this way 🤔 ?

**Comment by edhelas** [comment]
Also be careful because this route is used at several places (see `protectPicture()`)

**Comment by dos1** [comment]
I was making https://github.com/dos1/movim/commit/956383e31182e28cf819b9b7504275315f84ae45 and to test it, I have used first image files that appeared in the file dialog. Those turned out to be some 32x32 icons that didn't work because they were too small :P So I though it may make sense to replace that minimal size check with something more robust. I'll check out other places - I did some git grepping for them, but I could have missed it if it's constructed differently.

BTW. Is https://github.com/dos1/movim/commit/956383e31182e28cf819b9b7504275315f84ae45 something you would even consider merging? If not, I won't bother with PRing it :P

**Comment by edhelas** [comment]
Hi !
After those 4 years of silence I'm checking up this PR. Would it be possible to talk about it by chat, I'm still figuring out the final goal of this PR.

**Comment by Neustradamus** [comment]
@dos1: Have you seen the last @edhelas comment?

**Comment by edhelas** [comment]
The picture proxy was recently refactored, this should not be relevant anymore

**Pull request closed without merging**
