### PR TITLE
Make bubble icons non-selectable

### PR DESCRIPTION
**Pull request by dos1**

### CODE REVIEW

**Comment by edhelas** [comment]
But why?

**Comment by dos1** [comment]
It just looks like something broken when you select text from multiple balloons :P

**Comment by edhelas** [comment]
And you actually need to click on those icons in some places, like in the MUC widget.

**Comment by dos1** [comment]
...and `user-select` doesn't influence that in any way. It just makes the UI feel a bit more solid, as the placeholder text in the avatarless bubbles won't appear selected anymore.

**Comment by edhelas** [comment]
Well thanks…

**Pull request merged**
