### PR TITLE
Missing base URIs from favicons

### PR DESCRIPTION
**Pull request by toastal**
[^1]

[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project.
I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.

### CODE REVIEW

**Comment by edhelas** [comment]
linkFile is calling urilize that is already using BASE_URI, is this PR actually working ?

**Comment by toastal** [comment]
```console
> document.head.querySelector("link[rel=apple-touch-icon]").href
"https://movim.toastal.in.th/theme/img/app/192_square.png?t=1" 
```

Before it was just relative for me & `chat/theme/*` doesn’t exist

**Comment by toastal** [comment]
Y’know… I *do* recall the JavaScript not being able to find the favicon due to a relative path & just drawing the notification count over transparency, but I must have gotten in an odd state since peeling off this patch I was not able to reproduce.

**Comment by edhelas** [comment]
So everything is fine there, nothing to fix :)

**Pull request closed without merging**
