### PR TITLE
Prevent scroll down button from overlapping the send button (with mul…

### PR DESCRIPTION
**Pull request by ltguillaume**
…ti-line messages)

### CODE REVIEW

**Comment by edhelas** [comment]
Damn i need to review that one, sorry...

**Comment by ltguillaume** [comment]
No worries!

**Comment by ltguillaume** [comment]
@edhelas Auto-hiding the scroll button had to be fixed. This is now working. (I took the query `#chat_widget #scroll_down.button.action` directly from `chat.css`), so it's identical in `chat.js`.

**Comment by edhelas** [comment]
Can you please rebase and resolve the conflicts, i'll have a look :)

**Comment by ltguillaume** [comment]
Yeah should be fine now.

**Comment by edhelas** [comment]
Looks great. 
One last thing, to preserve the alignment with the + menu, can you please keep the existing position:

```css
    top: -6.5rem;
    right: 0.75rem;
```

**Comment by edhelas** [comment]
And please squash everything in one :) !

**Comment by ltguillaume** [comment]
Alrighty then.

**Pull request merged**
