### PR TITLE
added github actions

### PR DESCRIPTION
**Pull request by kskarthik**
* Added build job which builds movim from source
* runs on master branch when a commit or pull request is made

### CODE REVIEW

**Comment by kskarthik** [comment]
This is the build log https://github.com/kskarthik/movim/actions/runs/4077536180/jobs/7026677356

**Comment by kskarthik** [comment]
@edhelas Please review. i believe there are no tests of any sort, correct? if exists, i will also add them to ci pipeline

**Comment by kskarthik** [comment]
@edhelas let me know your opinion on this PR :)

**Comment by edhelas** [comment]
Looks fine to me :) 
Would it be possible to also add a small badge in the README or something ?

**Comment by kskarthik** [comment]
@edhelas done! made a new PR. This first need  to first and later that

**Pull request merged**
