### PR TITLE
Add <html lang>

### PR DESCRIPTION
**Pull request by toastal**
Important for screen readers, also helps in some spell checking & hyphenation scenarios
https://dequeuniversity.com/rules/axe/4.4/html-has-lang

[^1]

[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project.
I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.

### CODE REVIEW

**Comment by edhelas** [comment]
Is the injected language actually in the correct HTML format ? Thanks for the PR !

**Comment by toastal** [comment]
It appears to work for me getting both the app config & cat swap per user, but I can’t say it is easy for me to get my bearings around OO projects so it could be inefficient (but hopefully not wrong 🤞).
-- 
toastal ไข่ดาว | https://toast.al
PGP: 7944 74b7 d236 dab9 c9ef  e7f9 5cce 6f14 66d4 7c9e

**Comment by edhelas** [comment]
This should work, however Movim is having a few languages that doesn't respect the HTML standard (https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes)  such as zh_tw or ur_pk (see the list there https://github.com/movim/movim/tree/master/locales) 

Maybe it would be wise to only take the two first letters ?

**Comment by toastal** [comment]
Tough call, but I don’t think you want to lose the region code, but should prefer it when possible (i.e. I would open up an `en-US` translation if it were missing as I much prefer -ize, -or 😆). My preference would either be a second lookup table from current codes to ISO codes *or* rename the files to match the ISO standard (where a `s/_/-/` would be fine).

I would be curious to know (and not surprised) if the browser implicitly falls back to the first two when the region isn’t matched anyhow. In which case, so string manipulation on the locale can work until a better fix is in place.
-- 
toastal ไข่ดาว | https://toast.al
PGP: 7944 74b7 d236 dab9 c9ef  e7f9 5cce 6f14 66d4 7c9e

**Comment by toastal** [comment]
Actually I may take on this exploding of a string now.

**Pull request closed without merging**
