### PR TITLE
ci: build docker image on each commit

### PR DESCRIPTION
**Pull request by kskarthik**
1. this PR builds a docker image of movim for each commit & uploads to docker hub
2.  Image is tagged as `master` denoting the master branch

:warning:  NOTE: Before merging the PR,  create a auth token on docker hub with push rights & set the `DOCKER_HUB_TOKEN` secret in the repository.

### CODE REVIEW

**Comment by kskarthik** [comment]
@kawaii @edhelas please review

**Comment by kawaii** [comment]
Here's how I'd really prefer to do this;

- keep existing Dockerfile and entrypoint script in the original repo, albeit with some modifications
- merge only the CI part into this repo

Here's a rough draft of how you should modify the `Dockerfile` over in the movim_docker repo, it might need some adjustments to work correctly and I haven't tested it:
```
RUN set -ex; \
        if [ -n "$DEVBUILD" ]; then
                export MOVIM_VERSION = "master"; \
                git clone https://github.com/movim/movim /usr/src/movim-master
                chown -R www-data:www-data /usr/src/movim-${MOVIM_VERSION}
        else
                curl -o movim.tar.gz -fSL "https://github.com/movim/movim/archive/v${MOVIM_VERSION}.tar.gz"; \
                echo "$MOVIM_SHA512 *movim.tar.gz" | sha512sum -c -; \
                tar -xzf movim.tar.gz -C /usr/src/; \
                rm movim.tar.gz; \
                chown -R www-data:www-data /usr/src/movim-${MOVIM_VERSION}
        fi
```
In this case, if the `$DEVBUILD` environment variable is set, it'll clone the latest master branch and build from there. Hopefully this helps you enough to get something working.

**Comment by kskarthik** [comment]
@kawaii your idea is good, let me try that!

**Comment by kskarthik** [comment]
trying building with `docker build --build-args DEVBUILD=true`

the `WORKDIR` is not set to `/usr/src/movim-master` in later stages, instead using the default value

@kawaii  Where did i go wrong? :confused: 

# Code
image

# Error
image

**Comment by kskarthik** [comment]
I found the issue, patch incoming :rocket: !

**Comment by kskarthik** [comment]
Update: PR https://github.com/movim/movim_docker/pull/36 needs to be merged first, followed by changes to the docker action refactoring in this PR.

**Comment by kskarthik** [comment]
@edhelas  @kawaii i have updated this PR as well. Please review

Docker build is working. Logs https://github.com/kskarthik/movim/actions/runs/4808063312/jobs/8557577813

Please note to add `DOCKER_HUB_TOKEN` to repository before merging this

**Comment by kskarthik** [comment]
@kawaii Hi, any update on the docker auth token ?

**Pull request merged**
