### PR TITLE
Bug/corruptedAvatars

### PR DESCRIPTION
**Pull request by TheBluestBird**
I have an [issue](https://github.com/movim/movim/issues/1046) with my installation, it looks like a really distorted images for avatars.
The setup is like 
php 8.1.12 (but was appearing on earlier versions)
imagemagick 7.1.0.53 (but was appearing on earlier versions)
php-imagick 3.7.0 (but was appearing at least since 3.5.1)

This solution helps but I have no idea if it keeps things in order, please check it!

### CODE REVIEW

**Comment by edhelas** [comment]
Hi, those constants are only available since Image Magick 7.0. 
I'll have to add a test around to check the version. Can you please drop me there the return of this call:

```
var_dump(Imagick::getVersion());
```

For me I have this:

```
array (size=2)
  'versionNumber' => int 1691
  'versionString' => string 'ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org' (length=67)
```

**Comment by TheBluestBird** [comment]
Sure, here it is

```
array(2) {
  ["versionNumber"]=>
  int(1808)
  ["versionString"]=>
  string(66) "ImageMagick 7.1.0-53 Q16-HDRI x86_64 20646 https://imagemagick.org"
}
```

**Comment by edhelas** [comment]
I'd like to know what is the versionNumber of ImageMagick 7.0 then, for now I have no clue :/

**Comment by TheBluestBird** [comment]
You want to tell it specifically from int versionNumber?
Yeah, quick browsing didn't help me much, i'm going to look some more little later, maybe be there is some version map somewhere...

Would you consider a dirty hack if we check it from regexing versionString? We could do it once on the launch an save it as a constant, not to do it everytime on conversion

**Pull request closed without merging**
